#version: "3.8"
services:
    backend:
        env_file:
            - .env
        build:
            context: ./vendor/laravel/sail/runtimes/8.2
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: sail-8.2/app
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '8000:8000'
            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
            - '6001:6001'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
            IGNITION_LOCAL_SITES_PATH: '${PWD}'
        volumes:
            - '.:/var/www/html/backend'
            - './storage:/var/www/html/storage'
        networks:
            - sail
        depends_on:
            - mysql
            - redis
        restart: unless-stopped

    dashboard:
        build:
            context: ../dashboard
            dockerfile: Dockerfile
        ports:
            - '80:80'
        volumes:
            - '../dashboard:/var/www/html/dashboard'
        depends_on:
            - backend
        networks:
            - sail
        restart: unless-stopped

    mysql:
        env_file:
            - .env
        image: 'mysql/mysql-server:8.0'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - 'sail-mysql:/var/lib/mysql'
            - './vendor/laravel/sail/database/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
        networks:
            - sail
        healthcheck:
            test:
                CMD
                mysqladmin
                ping
                '-p${DB_PASSWORD}'
            retries: 3
            timeout: 5s

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: pma
        links:
            - mysql
        environment:
            PMA_HOST: mysql
            PMA_PORT: 3306
            PMA_ARBITRARY: 1
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
        restart: unless-stopped
        ports:
            - 8085:80
        networks:
            - sail

    redis:
        env_file:
            - .env
        image: 'redis:alpine'
        ports:
            - '${FORWARD_REDIS_PORT:-6379}:6379'
        volumes:
            - 'sail-redis:/data'
        networks:
            - sail
        healthcheck:
            test:
                CMD
                redis-cli
                ping
            retries: 3
            timeout: 5s
        restart: unless-stopped
#
#    imgproxy:
#        image: darthsim/imgproxy
#        ports:
#            - "9999:8080"
#        environment:
#            IMGPROXY_KEY: 0189f3c50ac42edd5a2dc5a83092eade7b1b41148b0997860c22acf2a09d61ee
#            IMGPROXY_SALT: cf755c9ebac65e2ce6df62037773bb60a39b3895cb299dcb46aee6bc78937c88
#            IMGPROXY_LOCAL_FILESYSTEM_ROOT: /var/www/html/storage/app/public
#        volumes:
#            - ./storage/app/public:/var/www/html/storage/app/public
#        restart: unless-stopped
#        networks:
#            - sail

    thumbor:
        image: apsl/thumbor
        ports:
            - "9999:8000"
        volumes:
            - ./thumbor.conf:/etc/thumbor.conf
#            - ./th.py:/th.py
            - ./storage/app/public:/var/www/html/storage/app/public
            - ./logs/thumbor:/var/log/thumbor
        environment:
            - THUMBOR_CONFIG=/etc/thumbor.conf
        restart: unless-stopped
        networks:
            - sail

    thumbor:
        image: apsl/thumbor
        ports:
            - "9999:8000"
        volumes:
            - ./thumbor.conf:/etc/thumbor.conf
#            - ./th.py:/th.py
            - ./storage/app/public:/var/www/html/storage/app/public
            - ./logs/thumbor:/var/log/thumbor
        environment:
            - THUMBOR_CONFIG=/etc/thumbor.conf
        restart: unless-stopped
        networks:
            - sail

#
#    imgproxy:
#        image: darthsim/imgproxy
#        ports:
#            - "9999:8080"
#        environment:
#            IMGPROXY_KEY: 0189f3c50ac42edd5a2dc5a83092eade7b1b41148b0997860c22acf2a09d61ee
#            IMGPROXY_SALT: cf755c9ebac65e2ce6df62037773bb60a39b3895cb299dcb46aee6bc78937c88
#            IMGPROXY_LOCAL_FILESYSTEM_ROOT: /var/www/html/storage/app/public
#        volumes:
#            - ./storage/app/public:/var/www/html/storage/app/public
#        restart: unless-stopped
#        networks:
#            - sail

networks:
    sail:
        driver: bridge
volumes:
    sail-mysql:
        driver: local
    sail-redis:
        driver: local
