<?php

namespace App\Constants;

class ConfigurationConstants
{
    const TIMEZONE = "timezone" ;
    const RESERVATIONS_MARGIN = "RESERVATIONS_MARGIN" ;

    const QR_ONESIGNAL_APP_ID = 'QR_ONESIGNAL_APP_ID';
    const QR_ONESIGNAL_REST_API_KEY = 'QR_ONESIGNAL_REST_API_KEY';
    const QR_ONESIGNAL_USER_AUTH_KEY = 'QR_ONESIGNAL_USER_AUTH_KEY';

    const ORDERS_ONESIGNAL_APP_ID = 'ORDERS_ONESIGNAL_APP_ID';
    const ORDERS_ONESIGNAL_REST_API_KEY = 'ORDERS_ONESIGNAL_REST_API_KEY';
    const ORDERS_ONESIGNAL_USER_AUTH_KEY = 'ORDERS_ONESIGNAL_USER_AUTH_KEY';



}
